

# Notes: 
# - pages with "nav: true" in front matter will be in header nav
# - use environment variable on build command to include analytics: JEKYLL_ENV=production jekyll build

# site settings
title: Zhang Lab @ Columbia
description: "The laboratory of Dr. Hanrui Zhang at Columbia University Irving Medical Center"
keywords: "github, laboratory, macrophage, genomics, Columbia, cardiometabolic diseases"

# author settings for cc-by
author: hz2418
pub_year: 2019
github_username: hanruizhang

# add the full url for the github repository
repo: "https://github.com/hanruizhang/zhanglab"

# urls
# your webpage url: https://username.github.io
url: https://hanruizhang.github.io
# your repository name: /repository
baseurl: /zhanglab

# analytics if desired (and use environment variable on build command)
# Stream name: Zhang Lab, on 11/30/2023
google-analytics-id: G-V0NP4ZQMME

# defaults (to simplify front matter)
defaults:
  - scope:
      path: ""
    values:
      layout: default

# Build settings
markdown: kramdown

theme: jekyll-theme-cayman
